### ISSUE TITLE
Tutorial: Tracing code [Optional]

### ISSUE THREAD

**Issue by Nature711** [AY2122S1-CS2103T-W17-1/tp#12]
Follow [Tutorial: Tracing code](https://nus-cs2103-ay2122s1.github.io/tp/tutorials/TracingCode.html) 
Post an issue in your team's repo with the title ``Tutorial: tracing code``. In the description, add a 2-3 screenshots you took while at various points of the tutorial. You may close the issue soon after.

**Comment by feliciaivane** [comment]
Everyone has completed the tutorial
