### ISSUE TITLE
Tutorial: Adding a new command

### ISSUE THREAD

**Issue by Nature711** [AY2122S1-CS2103T-W17-1/tp#13]
Follow [Tutorial: Adding a new command](https://nus-cs2103-ay2122s1.github.io/tp/tutorials/AddRemark.html)
Do your changes in a branch named ```tutorial-adding-command```, push to your fork, and create a PR from your fork to your team's repo. You may close the PR soon after.

**Comment by feliciaivane** [comment]
Everyone has completed the tutorial
