### ISSUE TITLE
[PE-D] Minor issue in documentation in the User Guide 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W17-1/tp#191]
For the soon feature, the user guide does not explicitly state that we should only type positive integers. The example given does show that but it would be better if it is also explicitly stated in the user guide. This is a minor issue but just thought I should raise it as well. 
![Screenshot 2021-10-29 at 4.40.35 PM.png](https://raw.githubusercontent.com/Neha-5678/ped/main/files/e3d7e927-8009-43c9-becc-1f18ec8fa71d.png)

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: Neha-5678/ped#3

**Comment by Nature711** [comment]
Solution:  explicitly state that `soon` command should only type positive integers
