### ISSUE TITLE
[PE-D] Edit after find jumps back to complete list

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W17-1/tp#194]
**Steps to reproduce:**
1. `edit 1 pr/low`
2. `edit 5 pr/low`
3. `find pr/low`
4. `edit 2 p/UI`

**Expected:**
Stays on filtered list

**Actual:**
Goes back to all-internships list

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: tanjiaxian99/ped#8

**Comment by tianyue58** [comment]
This behaviour is actually expected? Maybe we can state it clearly in UG.

**Comment by Nature711** [comment]
After `edit` command, the whole list will always be shown.
