### ISSUE TITLE
[PE-D] Suggestion to improve Documentation 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W17-1/tp#196]
The format for the INTERVIEW_DATE_AND_TIME and APPLICATION_DEADLINE was stated in the table at the top of the user guide. However, maybe it would help users if it is also stated under each section for the feature so that users will not have to scroll up and down. For instance, the format of the INTERVIEW_DATE_AND_TIME  was not explicitly stated in the edit section (view screenshot) 

![Screenshot 2021-10-29 at 4.49.36 PM.png](https://raw.githubusercontent.com/Neha-5678/ped/main/files/120779a1-5ad4-4351-abc3-ffd35991de89.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: Neha-5678/ped#4

**Comment by feliciaivane** [comment]
Hmm not sure if we should include all the details under each command, but what do you guys think?

**Comment by Nature711** [comment]
TBH I don't think it's necessary (?)
