### ISSUE TITLE
[PE-D] No error message thrown for invalid dates

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W17-1/tp#201]
**Steps to reproduce:**
1. `edit 1 d/2021-02-29`

OR 

1. `edit 1 d/2021-04-31`

**Expected:**
Error message for invalid date

**Actual:**
No error messages

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: tanjiaxian99/ped#9

**Comment by Nature711** [comment]
Cause: The validation regex used currently only checks if the day and month is in range [0, 31], [1, 12] respectively
Solution: Add additional validation for date format
Affected: `Deadline`, `InterviewDateAndTime` class
