### ISSUE TITLE
[PE-D] Find c1/ accepting nonsensical input

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W17-1/tp#202]
![image.png](https://raw.githubusercontent.com/huyuxin0429/ped/main/files/1429ac8b-430f-454b-81c5-9da706a6518e.png)

## Expected behaviour
Only valid input should be accepted in this field.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: huyuxin0429/ped#10

**Comment by Nature711** [comment]
Solution: Limit the accepted input of find c1/ to "COMPLETED" and "UNCOMPLETED"
Affected: `find` command
