### ISSUE TITLE
[PE-D] Undo and Redo do not check for invalid parameters

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W17-1/tp#207]
Users are able to input invalid command parameters

![image.png](https://raw.githubusercontent.com/bentanjunrong/ped/main/files/2f7d5ee4-07d7-497a-9790-ae7c8dcc1c2a.png)

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: bentanjunrong/ped#9

**Comment by Nature711** [comment]
Update UG
